language: android
os: linux
dist: trusty
notifications:
  email: true
android:
  components:
  - build-tools-30.0.2
  - android-30
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-30
before_script:
  - chmod +x gradlew
#- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
#- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
#cache:
#  directories:
#  - "$HOME/.gradle/caches/"
#  - "$HOME/.gradle/wrapper/"
#  - "$HOME/.android/build-cache"
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_69a4188f9733_key -iv $encrypted_69a4188f9733_iv
  -in /key/littlecorgi.jks.enc -out /key/littlecorgi.jks -d
