language: android
os: linux
dist: trusty
notifications:
  email: true
android:
  components:
  - build-tools-30.0.2
  - android-30
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-30
before_script:
- chmod +x gradlew
script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_1d5650018551_key -iv $encrypted_1d5650018551_iv
  -in littlecorgi.jks.enc -out key/littlecorgi.jks -d
